### PR TITLE
Don't special case the AL condition code, remove (inaccurate) ARM7 multiply carry flag behavior

### PR DESCRIPTION
**Pull request by wheremyfoodat**

### CODE REVIEW

**Comment by RSDuck** [comment]
what is the purpose behind this?

**Comment by Arisotura** [comment]
I recall that the AL special case makes it a bit faster (but might as well get rid of it if it's the kind of optimization that is tiny and CPU-dependent)

on the other hand, removing existing behavior because it's inaccurate? do we have hardware tests to confirm what the correct behavior is?

**Comment by wheremyfoodat** [comment]
> I recall that the AL special case makes it a bit faster (but might as well get rid of it if it's the kind of optimization that is tiny and CPU-dependent)
> 
> on the other hand, removing existing behavior because it's inaccurate? do we have hardware tests to confirm what the correct behavior is?

Endrift ran some tests on the GBA ARM7 in December or so iirc and the results were absolutely wack, don't think the carry flag behavior was ever fully discovered.

**Comment by Arisotura** [comment]
don't see any point in removing it either. you never know when that'll unexpectedly break something. my policy is to either keep things as they are (based on available documentation) or reimplement them based on hardware tests. I don't want to change the emulation behavior without any base that isn't an assumption.

**Comment by wheremyfoodat** [comment]
Oh, no problem <3

**Comment by endrift** [comment]
I can confirm, the behavior of the carry flag with mul is very very strange, but I have yet to figure out the proper behavior.

**Pull request closed without merging**
