### PR TITLE
Fix issue on macOS with needing explicit cast

### PR DESCRIPTION
**Pull request by gbear605**
Was having an error

> non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]

### CODE REVIEW

**Comment by WaluigiWare64** [comment]
What does this fix?
melonDS builds fine on macOS, both here and on the CI.

**Comment by gbear605** [comment]
The main branch on the CI is not currently building correctly, and I had the same issue on my local computer. See https://github.com/Arisotura/melonDS/runs/1636285106

The full error messages shown is

```
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:878:23: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
        0,   192,  0, 0.5 - padPixels,
                      ^~~~~~~~~~~~~~~
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:878:23: note: insert an explicit cast to silence this issue
        0,   192,  0, 0.5 - padPixels,
                      ^~~~~~~~~~~~~~~
                      static_cast<float>( )
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:879:23: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
        256, 192,  1, 0.5 - padPixels,
                      ^~~~~~~~~~~~~~~
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:879:23: note: insert an explicit cast to silence this issue
        256, 192,  1, 0.5 - padPixels,
                      ^~~~~~~~~~~~~~~
                      static_cast<float>( )
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:881:23: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
        256, 192,  1, 0.5 - padPixels,
                      ^~~~~~~~~~~~~~~
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:881:23: note: insert an explicit cast to silence this issue
        256, 192,  1, 0.5 - padPixels,
                      ^~~~~~~~~~~~~~~
                      static_cast<float>( )
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:884:23: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
        0,   0,    0, 0.5 + padPixels,
                      ^~~~~~~~~~~~~~~
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:884:23: note: insert an explicit cast to silence this issue
        0,   0,    0, 0.5 + padPixels,
                      ^~~~~~~~~~~~~~~
                      static_cast<float>( )
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:887:23: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
        0,   0,    0, 0.5 + padPixels,
                      ^~~~~~~~~~~~~~~
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:887:23: note: insert an explicit cast to silence this issue
        0,   0,    0, 0.5 + padPixels,
                      ^~~~~~~~~~~~~~~
                      static_cast<float>( )
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:889:23: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
        256, 0,    1, 0.5 + padPixels
                      ^~~~~~~~~~~~~~~
/Users/runner/work/melonDS/melonDS/src/frontend/qt_sdl/main.cpp:889:23: note: insert an explicit cast to silence this issue
        256, 0,    1, 0.5 + padPixels
                      ^~~~~~~~~~~~~~~
                      static_cast<float>( )
6 errors generated.
```

**Comment by WaluigiWare64** [comment]
Yep, you are right.
I edited my comment.

**Comment by RSDuck** [comment]
my bad. I fixed it myself by doing the whole operation in floats instead of casting the double result back to floats. Thank you anyway.

**Pull request closed without merging**
