### PR TITLE
Add GitHub workflow configurations for continuous integration with Linux and Windows

### LINKED ISSUE #301: Hate to ask this but.. is there a CI Server
I dont see a CI Server, but it might be a smart move since im using a windows machine and CMake is such a jerk to me. Not your codebase but in general. Or atleast add a compilation guide

### LINKED ISSUE #387: Autobuilds
Maybe melonds could have autobuilds.
Desmume uses https://www.appveyor.com/ and it's free for open source projects

### LINKED ISSUE #540: GitHub Actions support
Add GitHub Actions support for automated builds.

### PR DESCRIPTION
**Pull request by rzumer**
This enables continuous integration with GitHub Actions, allowing developers to see if their commits/PRs are breaking the build.
Example run [here](https://github.com/rzumer/melonDS/commit/7027813cb268c8b168a2c6ac7e871761f02a4435/checks?check_suite_id=353617464).

Both Linux and Windows are included, and the compiled binaries are exported with shared libraries and `romlist.bin`.

Closes #540, closes #301 and closes #387.

### CODE REVIEW

**Comment by MojoJojoDojo** [comment]
I am not sure @Arisotura gonna merge it.
He doesn't want to maintain it.

**Comment by RSDuck** [comment]
It's only a single file, if we want to remove it again, it won't be that hard. If Arisotura, doesn't want to maintain it I would keep an eye on it too.

**Comment by rzumer** [comment]
> Btw I read this PR from another project : [xqemu/xqemu#266](https://github.com/xqemu/xqemu/pull/266)
> I think there is a way to get MSYS2 working than.

Cool, I will look into it.

**Comment by RSDuck** [comment]
can you also enable building for pull requests?

**Comment by poudink** [comment]
isn't arisotura a windows user? a linux-only developer feature isn't going to be very useful to her in that case.

**Comment by rzumer** [comment]
Added a Windows configuration. It fetches MSYS2 from XQEMU because the official MSYS2 distribution packages cause CI to fail due to permission errors which I haven't managed to solve. It does not export artifacts at this point.

**Comment by rzumer** [comment]
Now exporting build artifacts (dependencies not included).

**Comment by RSDuck** [comment]
> isn't arisotura a windows user? a linux-only developer feature isn't going to be very useful to her in that case.

I'm using Windows too. But 99% of the code of melonDS is shared amongst platforms, even if we wouldn't have Windows CI builds (thanks for that), we would still benefit (almost always) by knowing whether a pull requests builds or not.

**Comment by RSDuck** [comment]
it seems like you're currently only putting the exe file as artefacts, can you add the romlist.bin and for Windows the appropriate dlls (see https://github.com/Arisotura/melonDS/blob/master/msys-dist.sh) too and put everything into a zip file or so?

**Comment by rzumer** [comment]
@RSDuck Done now, sorry if someone got flooded by emails because of my force-pushes.

**Comment by MojoJojoDojo** [comment]
I think you should clone the XQEMU repo and not use it as is lol.

**Comment by rzumer** [comment]
I'm not interested in maintaining a redundant package. If @Arisotura wants to do that in parallel feel free, but energy would be better spent in finding a way to run off the official distribution packages, and I fought with it enough for now.

**Pull request merged**
