### PR TITLE
Fix hanging UI when `null` addr

### PR DESCRIPTION
**Pull request by i404788**
See https://github.com/Arisotura/melonDS/issues/532

### CODE REVIEW

**Comment by Arisotura** [comment]
pls adapt it to the overall melonDS code style (namely, opening brace goes on a new line), and I will merge this

**Comment by i404788** [comment]
done

**Comment by rzumer** [comment]
The indentation seems wrong.

**Comment by i404788** [comment]
You are right, I missed that when cleaning up

**Pull request merged**
