### PR TITLE
Fallback to FreeBIOS when BIOS files are not found.

### PR DESCRIPTION
**Pull request by Swordfish90**
This pull request, together with #778 makes melonDS no longer reliant on external files, effectively closing #367 .

I've tested the free BIOSes on dozens of games these days and each one of them worked correctly.

This is the free BIOS that's bundled with Drastic, which has more than 1M downloads on Google Play so it should be quite battle-tested.

### CODE REVIEW

**Comment by WaluigiWare64** [comment]
Could you make an option like "Use FreeBIOS instead of external BIOS and firmware"?
Let's say I want to test the FreeBIOS, but I don't want to remove my DS config and then re add them later.

**Comment by g4jc** [comment]
I apologize if this is an obvious question, but is FreeBIOS really free? It appears to be a hex blob, but I was unable to find the original sources. In fact even the APK for Drastic cost $4.99 and there is no source code for it either.

**Comment by nadiaholmquist** [comment]
Yes it is actually free (BSD license if I remember right) but I think it's only distributed in the DraStic APK. Might be a good idea to throw that source up on GitHub too.

**Comment by Swordfish90** [comment]
@g4jc @nadiaholmquist You can find the source code (with the license) in the referenced GitHub issue, but I'll also include it within this pull request later today just to be on the safe side.

**Comment by FrostKnight** [comment]
@Swordfish90 so it is legal? That's good, Don't want a good ds emulator like melonds dying.

**Comment by Swordfish90** [comment]
@FrostKnight I understand the concearns, I'd also really like to see melonDS flourish. 

I don't think there is a problem with Nintendo. We have the source code of this project and Drastic, which is a paid application on Google Play with more than 1M downloads hasn't received a DMCA for it.

Drastic is also bundling the binary and the source code together with their APK. The license is pretty permissive and clear (it's included in the header file in this pull request).

IMHO only a minority of users today are using a legal bios file dumped from their own console, so I believe this is a step towards legal usage.

**Comment by FrostKnight** [comment]
Can I see the source code? I am curious what website still has it up.

**Comment by xperia64** [comment]
> 
> 
> Can I see the source code? I am curious what website still has it up.

https://github.com/Arisotura/melonDS/issues/367#issuecomment-509061317

**Comment by Swordfish90** [comment]
Hi guys. @g4jc @nadiaholmquist I added the bios source and binary files to the pull request.

Feel free to let me know if you need anything else on my side.

**Comment by SuuperW** [comment]
Is there anything else that should be done before merging this and #778? I'd like to see that happen.

**Comment by poudink** [comment]
what does this do that https://github.com/Arisotura/melonDS/pull/778/ doesn't do?

**Comment by RSDuck** [comment]
> what does this do that #778 doesn't do?

both PRs are complementary. This one's for bios files, the other one for the firmware.

**Comment by Swordfish90** [comment]
To give you a short update, these two pull requests have been battle-tested in Lemuroid (in production) for the last two months (where you can't even specify a different BIOS file).

Just let me know what's your take on this, I can fix the merge conflicts, or I won't hold a grudge if you decide not to keep it.

**Comment by RSDuck** [comment]
is FreeBIOS really the name of the bios replacement? It seems to appear nowhere in it's files. Otherwise I think we can merge this.

**Comment by Swordfish90** [comment]
@RSDuck I don't think it has a proper name, so I went with the most obvious "FreeBIOS". We can call it "Drastic BIOS" or "Custom BIOS replacement" or any combination of the previous. Which one would you suggest?

**Comment by RSDuck** [comment]
call it Drastic BIOS, that's a pretty unambigious name.

**Comment by WaluigiWare64** [comment]
I think that instead of the BIOS replacement being loaded automatically when BIOS files are not provided, there should be an option.
image
(quick sketch in paint)

Also should the BIOS replacement files be in a folder under the root or src?

The makefile is unnecessary, so that can be removed.

**Comment by Arisotura** [comment]
I'd rather call it 'internal BIOS', 'BIOS replacement' makes it sound like it's meant to replace something, and imo sounds less intuitive to the average joe

**Comment by nadiaholmquist** [comment]
Agreed, that or "built-in BIOS". There should probably also be a warning under the box that it's not entirely accurate to the original DS BIOS, and that using the official BIOS is recommended if you can get a hold of it.

**Comment by WaluigiWare64** [comment]
We don't really need to call it something, seeing as we all have different opinions on this:
image

**Comment by Parakoopa** [comment]
I like the solution by @WaluigiWare64 best. Just have a checkbox that when unchecked greys out the other controls and uses the Drastic BIOS, and this should be the default.

**Comment by vadosnaprimer** [comment]
Did https://github.com/Arisotura/melonDS/pull/1174 resolve this PR?

**Comment by RayyanAnsari** [comment]
merged in #1174

**Pull request closed without merging**
