### PR TITLE
Compilation on Windows with MSVC makefile

### PR DESCRIPTION
**Pull request by KrossX**
A few changes and a simple NMAKE makefile for compilation on Windows. A better alternative to issue #272 as it's easier to see if it's outdated.

### CODE REVIEW

**Comment by MojoJojoDojo** [comment]
Needs detailed instructions for usage.

**Comment by KrossX** [comment]
With the dev command prompt and extra includes/libs path set, you just run `nmake` in that directory.

**Comment by RSDuck** [comment]
why can't cmake be used for this? What if a new file is added, now both the cmake and the nmake script need to be maintained. Preventing those situation was the reason build script generators like cmake were invented.

**Comment by KrossX** [comment]
Not meant to be merged actually and I've been maintaining it, see the referenced issue. I made it for myself, as I don't like to use cmake, and shared in case it might be of use to someone else.

**Pull request closed without merging**
