### PR TITLE
Disable CI on non-master branches

### PR DESCRIPTION
**Pull request by rzumer**
This makes automated builds run only on pushes and pull requests to the master branch.

### CODE REVIEW

**Comment by nathanielcwm** [comment]
Whats wrong the the ci running on the other branches?

**Comment by RSDuck** [comment]
it's annoying

**Comment by nathanielcwm** [comment]
Oh looks like free github accounts only have 2000 minutes per month too.

**Comment by nathanielcwm** [comment]
Nevermind that's only for private repos

**Comment by nathanielcwm** [comment]
I see what you mean.

**Pull request merged**
