### PR TITLE
[DO NOT MERGE] Improve CLI

### PR DESCRIPTION
**Pull request by Anuskuss**
This is just so I can snag a build and finally delete DeSmuME. Code is trash so don't merge, but until that feature gets done users can use this instead.

### CODE REVIEW

**Comment by RSDuck** [comment]
for situations like this you can mark your PR as draft

**Comment by Anuskuss** [comment]
@RSDuck I don't think drafts get built.

**Comment by RSDuck** [comment]
oh right, though why don't build it on your computer then?

**Comment by Anuskuss** [comment]
To pressure you guys to implement it properly 😛. Jokes aside, this is quicker (for me) because I don't have to download and setup MSYS2+Qt (which is probably more than 10 GB in size) and maybe other users would be interested in a quick and dirty solution too (linking #237).

**Comment by WaluigiWare64** [comment]
Draft pull requests do build by the way.

**Comment by Anuskuss** [comment]
@RSDuck Can you go ahead and merge #933? Otherwise I'll probably add it here.

**Comment by Anuskuss** [comment]
I've added more (disgusting) code to fill in the gaps.

**Comment by Anuskuss** [comment]
Sad, it looks like from now on I need your approval if I want a new build. Please let me know if you want to give me the build permission or if I should nuke this entire thing as it's getting pretty ugly.

**Comment by RSDuck** [comment]
I mean pushing stuff to github to let it be build here (which will take a couple of minutes) is just a terrible workflow. Besides you merged in a PR which doesn't build on macos.

**Comment by Anuskuss** [comment]
I mean yeah, it's a terrible workflow but I don't have the space to set up MSYS2+Qt (256GB SSD) and lack the knowledge to properly use Git (or write good code for that matter). Why can't you just either accept my dumb code as it solves some serious QoL issues or just give me the build permission since it doesn't really hurt anyway?

**Comment by WaluigiWare64** [comment]
Fork the melonDS repo, enable workflows on your fork, then run it there.

**Comment by fancythedeveloper** [comment]
github drama lo

**Comment by Anuskuss** [comment]
Okay, looks like you were right - it does indeed build on my own fork. I'd still like to see these changes in upstream, but atleast *I* can get a build now. Now the question is: how do I nuke this without deleting the `patch-1` branch? I'd like to keep a reference of my commits but I can just create a local copy if need be.

**Comment by RSDuck** [comment]
the whole git history is a mess, I would just create a new branch where you would manually put in only your own changes.

**Comment by Anuskuss** [comment]
I just created a new commit on `patch-1` and it fortunately does not update this PR. Honestly, that's good enough for me because I don't wanna annoy you guys more than I already did and I don't care about the history/code as long as it works.

**Comment by fancythedeveloper** [comment]
> Okay, looks like you were right - it does indeed build on my own fork. I'd still like to see these changes in upstream, but atleast _I_ can get a build now. Now the question is: how do I nuke this without deleting the `patch-1` branch? I'd like to keep a reference of my commits but I can just create a local copy if need be.
> 
> > github drama lo
> 
> **Edit:** No drama here. Just a beginner struggling to contribute.

I was joking but alr.

**Comment by Anuskuss** [comment]
Haven't been following the project much this year but I got a notification that v0.9.5 dropped so I decided to check it out. And it looks like [all things I've hacked up](https://github.com/melonDS-emu/melonDS/pull/1394#issuecomment-1066002016) have been finally implemented properly. Good job team!

**Pull request closed without merging**
