### PR TITLE
Make melonDS properly installable systemwide on UNIX systems

### PR DESCRIPTION
**Pull request by nadiaholmquist**
This pull request adds a `UNIX_PORTABLE` option to CMake, turning it off builds a version of melonDS that is suitable for system-wide installation, by making it look for the firmware/config/etc. in the user's configuration and data directories rather than the current working directory like it normally does.

### CODE REVIEW

**Comment by PoroCYon** [comment]
Not exactly working yet:

```strace
18758 openat(AT_FDCWD, "melonDS.ini", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/usr/bin/melonDS.ini", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/home/poro/.config/melonds/melonDS.ini", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "bios7.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/usr/bin/bios7.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/home/poro/.config/melonds/bios7.bin", O_RDONLY) = 19
18758 openat(AT_FDCWD, "/home/poro/.config/melonds/bios7.bin", O_RDONLY) = 20
18758 dup3(20, 19, 0)                   = 19
18758 close(20)                         = 0
18758 close(19)                         = 0
18758 openat(AT_FDCWD, "bios9.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/usr/bin/bios9.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/home/poro/.config/melonds/bios9.bin", O_RDONLY) = 19
18758 openat(AT_FDCWD, "/home/poro/.config/melonds/bios9.bin", O_RDONLY) = 20
18758 dup3(20, 19, 0)                   = 19
18758 close(20)                         = 0
18758 close(19)                         = 0
18758 openat(AT_FDCWD, "firmware.bin", O_RDONLY) = 19
18758 openat(AT_FDCWD, "firmware.bin", O_RDONLY) = 20
18758 dup3(20, 19, 0)                   = 19
18758 close(20)                         = 0
18758 close(19)                         = 0
18758 openat(AT_FDCWD, "firmware.bin.bak", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/usr/bin/firmware.bin.bak", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/home/poro/.config/melonds/firmware.bin.bak", O_RDONLY) = 19
18758 openat(AT_FDCWD, "/home/poro/.config/melonds/firmware.bin.bak", O_RDONLY) = 20
18758 dup3(20, 19, 0)                   = 19
18758 close(20)                         = 0
18758 close(19)                         = 0
18758 openat(AT_FDCWD, "romlist.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/usr/bin/romlist.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
18758 openat(AT_FDCWD, "/home/poro/.config/melonds/romlist.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by KAMiKAZOW** [comment]
flatpak/net.kuribo64.melonds.desktop exists already. I suggest to add the missing lines there and reuse that file.

**Comment by Nadia-h** [comment]
I guess? I didn't use it so I didn't have to use the flatpak naming scheme.

Does anyone even use the flatpak stuff? It hasn't been updated to point at the new repository URL, and even if it did it still doesn't build.

**Comment by KAMiKAZOW** [comment]
> so I didn't have to use the flatpak naming scheme.

There is no Flatpak naming scheme. Reverse domain name notation is a long-standing standard no Linux desktop has any problems with:

Screenshot_2019-12-07_15-38-36

**Comment by Nadia-h** [comment]
There, I've removed the redundant desktop file and renamed it so it'll work fine with flatpak and regular installations, how about this?

**Pull request merged**
