### PR TITLE
Made randomizing the MAC address optional.

### PR DESCRIPTION
**Pull request by WouterPeeters9**
Fixes Arisotura/melonDS#447

This is my first time working in C++, so I don't know if I've broken any code laws.
I can confirm that this fixes the anti-time travel bug in Pokémon Platinum though.

### CODE REVIEW

**Comment by RSDuck** [comment]
looks good, though I wonder whether it is a good idea to hardcode the MAC address if it's not randomised @Arisotura

**Comment by nathanielcwm** [comment]
What about using the systems MAC address?

**Comment by JamesTheAwesomeDude** [comment]
Some ideas:

* Use the host's MAC ("lowest-indexed" card would probably hold water)
* Use whatever the ROM has burned-into it (allow changing/setting it?)

**Comment by InfamousKnight** [comment]
Is there anything else that needs to be done to get this merged?

**Comment by RSDuck** [comment]
we'll implement it properly ourselves in the new QT frontend.

**Comment by Arisotura** [comment]
I redid it but for the new UI, sorry that your PR didn't make it in in time

**Pull request closed without merging**
