### PR TITLE
Firmware editor

### PR DESCRIPTION
**Pull request by kyandora**
Addresses https://github.com/Arisotura/melonDS/pull/778#issuecomment-703165075.

### CODE REVIEW

**Comment by WaluigiWare64** [comment]
Is this not the same as #778?

**Comment by kyandora** [comment]
We both started at the same time, but ended with different approaches.
If no firmware is present, @Swordfish90 creates an empty dummy firmware in memory and populates it's user settings.
My pull request updates an already existing firmware file.

**Comment by kyandora** [comment]
@RSDuck @Swordfish90 What would you think about a hybrid approach with the user settings as an overlay on top of either the dummy or firmware? melonDS already does that with the touchscreen calibration data.

**Comment by RSDuck** [comment]
#778 already does that mostly

**Comment by kyandora** [comment]
In that case I'll close this and push all reusable parts to #778.

**Comment by Swordfish90** [comment]
@kyandora Yeah, they look very close. My main intent was making melonDS useable without a firmware (and using the free bios). If you want to submit the pull request with the UI on my fork, I'll merge them into one with both the in-memory firmware and the configuration (which in your case seems a bit more advanced).

**Pull request closed without merging**
